### ISSUE TITLE
Doesn't work in Opal 0.11

### ISSUE THREAD

**Issue by sfcgeorge** [fkchang/opal-hot-reloader#16]
The [React.rb patches](https://github.com/fkchang/opal-hot-reloader/blob/fc099b3d8ea5c2a1cba4b12c646a7fa0198e31d2/opal/opal_hot_reloader/reactrb_patches.rb) use invalid Ruby syntax - module definition within method body.

It results in this error on boot:

```
=> Booting Puma
=> Rails 5.1.4 application starting in development 
=> Run `rails server -h` for more startup options


##########################################################################
      HYPERLOOP LIBRARIES PRECOMPILING AND MINIFYING
  FIRST TIME BOOTING YOUR APP IT CAN TAKE 1 OR 2 MINUTES
 NB: You can force precompiling again by cleaning cache: rm -rf tmp/cache 
##########################################################################

Compiling the system assets for hyperloop-prerender-loader-system-code
opal_hot_reloader/reactrb_patches:7:9: error: module definition in method body
opal_hot_reloader/reactrb_patches:7:         module ClassMethods
opal_hot_reloader/reactrb_patches:7:         ^~~~~~             
Exiting
/Users/sfcgeorge/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/parser-2.3.3.1/lib/parser/diagnostic/engine.rb:71:in `process': module definition in method body (SyntaxError)
```

The reason is Opal 0.11 [changed](https://github.com/opal/opal/blob/master/CHANGELOG.md) parser to a more correct one:

"Removed self-written lexer/parser. Now uses parser/ast gems to convert source code to AST. (#1465)"

**Comment by fkchang** [comment]
@sfcgeorge Thanks for reporting this, I have a fix I think will do it, but I don't have a quick way to test on opal 0.11 - I tested it on 0.10.4 and it is still backwards compatible. If you 're able to test I could push it github, else it will have to wait until I'm able setup a testing situation

**Comment by sfcgeorge** [comment]
Yeah I should be able to test that this error goes away.

Hyperloop itself doesn't work with Opal 0.11 so I can't test that it "works" as a whole, but fixing this error is a start. It's not valid in regular MRI either:

```ruby
pry(main)> def foo
pry(main)*   module Bar
pry(main)*   end  
pry(main)* end  
# SyntaxError: (eval):3: module definition in method body
pry(main)> foo
# NameError: undefined local variable or method `foo' for main:Object
pry(main)> Bar
# NameError: uninitialized constant Bar
```

**Comment by sfcgeorge** [comment]
Beta versions of Hyperloop now support Opal 0.11 so I am able to test this, if you have time to push.

**Comment by sfcgeorge** [comment]
I've got a patch that somewhat works here https://github.com/joblabteam/opal-hot-reloader/tree/monkeypatch

It gets as far as "Reloading ruby ..." but then raises this error (Hyperloop lap16, Opal 0.11):
```
Uncaught TypeError: Cannot read property '$!' of undefined
    at TMP_1 (should_component_update.rb:32)
    at Object.Opal.yieldX (runtime.self-76343df8ed0f0e99f2f654f5d79a5ff7cacc9eaed06aaccdc41ca4e32e4a7d72.js?body=1:1411)
    at state.rb:137
    at singleton_class_alloc.$$set_state_context_to [as $set_state_context_to] (state.rb:129)
    at Opal.send (runtime.self-76343df8ed0f0e99f2f654f5d79a5ff7cacc9eaed06aaccdc41ca4e32e4a7d72.js?body=1:1605)
    at $Router.TMP_ShouldComponentUpdate_should_component_update$q_2 (should_component_update.rb:27)
    at api.rb:76
    at $writer.shouldComponentUpdate (api.rb:76)
    at react.self-be891b41053bb629e9e13e6c6919254346aabbcc8dcea05550be110a71ed0fd6.js?body=1:16121
    at measureLifeCyclePerf (react.self-be891b41053bb629e9e13e6c6919254346aabbcc8dcea05550be110a71ed0fd6.js?body=1:15572)
```

**Comment by fkchang** [comment]
@sfcgeorge do you know what the actual call to $! is, the error message implies it's trying to call $! of an undefined object

**Comment by sfcgeorge** [comment]
I’m seeing the same error in Hyperloop without opal hot reloaded, so I think the issue is there. As I’m seeing the “reloaded” logged, I guess my patch here might actually be working fine 😊

So perhaps wait until I can get the rest of Hyperloop working.

**Comment by zw963** [comment]
@sfcgeorge , hi, I tested in a little rackup app, this patch is worked with opal 0.11.

**Comment by fkchang** [comment]
@zw963 did your rackup app include hyper-react?

**Comment by zw963** [comment]
@fkchang , no, just a very simple app for test opal 0.11 worked with hot-reloader.

**Comment by fkchang** [comment]
@zw963 the reason I ask is that the monkey patch is specifically to make it so hyper-react works correctly when hot reloaded. That it works under plain opal, shows the syntax of the patch will run on 0.11 but not necessarily that React.rb has been properly patched

**Comment by sfcgeorge** [comment]
@fkchang I confirm my patch does work with the latest Hyperloop beta. If you can find a better way of fixing it that's fine too.

**Comment by zw963** [comment]
Cool, i think if hyperloop beta is work, it should merge as quick as possible, 

anyway, can work is better than not work

**Comment by fkchang** [comment]
I'll merge it, if I have time, I might look at a different way of fixing it

**Comment by fkchang** [comment]
I copied the file from @sfcgeorge 's fork and committed, if you can verify it still works, we're good.  Thanks

**Comment by zw963** [comment]
@fkchang , worked with: `gem 'opal_hot_reloader', github: 'fkchang/opal-hot-reloader'`.

Does any plan to release fixed version into rubygems?

**Comment by fkchang** [comment]
@zw963 just released 0.1.5
